StackLayout:
    orientation:'tb-lr'
    padding:10
    spacing:5
    Button:
        text:'Buuton 1'
        size_hint: 0.2,0.4
        width:100

    Button:
        text:'Buuton 2'
        size_hint: 0.2,0.4
    Button:
        text:'Buuton 3'
        size_hint: 0.2,0.4
    Button:
        text:'Buuton 4'
        size_hint: 0.2,0.4
    Button:
        text:'Buuton 5'
        size_hint: 0.2,0.4
    Button:
        text:'Buuton 6'
        size_hint: 0.2,0.4
