BoxLayout:
    orientation:'vertical'
    TextInput:
        text:'Single Line Input'
        multiline:False

    TextInput:
        text:'Single Line Input, start typing'
        background_color:0.8,0.8,0,1
        size_hint: 1,3
    TextInput:
        text:'Password'
        password: True
        multiline: False
        on_text:viewer.text = self.text

    TextInput:
        id: viewer
        readonly: True
        text:'edit the password'