
RootWidget:
    container: container
    BoxLayout:
        id : container
        orientation:'vertical'
        padding:0
        spacing:3
        Label:
            text: 'salah'

        BoxLayout:
            size_hint:1,0.1
            orientation:'horizontal'
            padding:0
            spacing:1

            Button:
                size_hint: 0.2,1
                text:'next'
                on_release:app.next_screen('1')